const fs = require('fs');
const path = require('path');

const jaipurMilestones = [
    {
        id: 1,
        name: "Hawa Mahal (Palace of Winds)",
        category: "Heritage Architecture",
        coords: [26.9239, 75.8267],
        timings: "09:00 AM - 05:00 PM (Daily)",
        entryFee: { budget: 50, standard: 200, foreign: 500 },
        travelTimeFromPrev: "Start Point / 15 mins from City Center",
        transitMode: "Public Bus 9A / E-Rickshaw (₹20)",
        googleRating: 4.6,
        reviewsCount: "94,000+",
        proTip: "Visit before 10:00 AM to capture morning sunlight reflecting on the pink honeycomb windows.",
        busAvailability: "High - Direct Stop: Badi Chaupar Bus Stand",
        description: "Iconic five-story palace built in 1799 with 953 windows (jharokhas) designed for royal women to observe street festivals secretly."
    },
    {
        id: 2,
        name: "City Palace of Jaipur",
        category: "Royal Residence & Courtyards",
        coords: [26.9258, 75.8237],
        timings: "09:30 AM - 05:00 PM & 07:00 PM - 10:00 PM (Night Tour)",
        entryFee: { budget: 150, standard: 300, foreign: 700 },
        travelTimeFromPrev: "8 mins walk (600m) from Hawa Mahal",
        transitMode: "Walking / Heritage Walkway",
        googleRating: 4.7,
        reviewsCount: "82,500+",
        proTip: "Get the composite ticket at entry to skip secondary lines at Jantar Mantar and Albert Hall.",
        busAvailability: "City Bus Route 1, 2, 9 stop right outside Sireh Deori Gate",
        description: "Sprawling royal complex of courtyards, Chandra Mahal, Mubarak Mahal, and museum galleries preserving Maharaja regalia."
    },
    {
        id: 3,
        name: "Jantar Mantar Astronomical Observatory",
        category: "UNESCO World Heritage Site",
        coords: [26.9248, 75.8246],
        timings: "09:00 AM - 05:00 PM (Daily)",
        entryFee: { budget: 50, standard: 100, foreign: 200 },
        travelTimeFromPrev: "4 mins walk (300m) from City Palace Gate",
        transitMode: "Walking",
        googleRating: 4.7,
        reviewsCount: "62,000+",
        proTip: "Hire an audio guide or certified astronomy guide to understand how the giant stone sundial measures time to 2-second accuracy.",
        busAvailability: "Badi Chaupar Bus Stop (400m walk)",
        description: "Historic 18th-century observatory built by Maharaja Sawai Jai Singh II featuring the world's largest stone sundial."
    },
    {
        id: 4,
        name: "Albert Hall Museum (Central Museum)",
        category: "Indo-Saracenic Art & History",
        coords: [26.9116, 75.8195],
        timings: "09:00 AM - 05:00 PM & 07:00 PM - 10:00 PM (Night Illumination)",
        entryFee: { budget: 40, standard: 150, foreign: 300 },
        travelTimeFromPrev: "10 mins transit (2.2 km) via Sanganeri Gate",
        transitMode: "E-Rickshaw / Bus Route 2 (₹15)",
        googleRating: 4.6,
        reviewsCount: "58,000+",
        proTip: "View the museum at night when exterior facade is bathed in colorful changing LED lights with hundreds of pigeons.",
        busAvailability: "Bus Route 2 & Ajmeri Gate feeder buses stop directly at Ram Niwas Garden",
        description: "Rajasthan's oldest museum housed in magnificent Indo-Saracenic architecture showcasing rare carpets, Egyptian mummy, and metal crafts."
    },
    {
        id: 5,
        name: "Amer Fort & Maota Lake",
        category: "UNESCO Hilltop Fortress & Palaces",
        coords: [26.9855, 75.8513],
        timings: "08:00 AM - 05:30 PM & 06:30 PM - 09:15 PM (Light & Sound)",
        entryFee: { budget: 100, standard: 250, foreign: 550 },
        travelTimeFromPrev: "25 mins drive (11 km) via Amer Road",
        transitMode: "AC Bus Route AC-5 or Uber/Auto (₹150)",
        googleRating: 4.8,
        reviewsCount: "135,000+",
        proTip: "Book the 7:00 PM English/Hindi light and sound show for a spectacular historic narration over Maota Lake.",
        busAvailability: "AC Low-Floor Bus AC-5 runs every 10 mins from Ajmeri Gate to Amer Fort",
        description: "UNESCO World Heritage fortress perched high on a hill, renowned for Sheesh Mahal (Mirror Palace) and Rajput architecture."
    },
    {
        id: 6,
        name: "Jaigarh Fort & Jaivana Cannon",
        category: "Hilltop Military Fortress",
        coords: [26.9850, 75.8456],
        timings: "09:00 AM - 05:00 PM (Daily)",
        entryFee: { budget: 70, standard: 150, foreign: 300 },
        travelTimeFromPrev: "12 mins uphill drive / connected tunnel from Amer Fort",
        transitMode: "Fort Shuttle / Auto / Taxi",
        googleRating: 4.6,
        reviewsCount: "44,000+",
        proTip: "Stand on the fort ramparts overlooking Amer Fort and Maota Lake for unmatched aerial photo panoramas.",
        busAvailability: "Shuttle cabs connect from Amer Fort base parking",
        description: "Imposing military fortress housing Jaivana, once the world's largest cannon on wheels, and ancient armory storage vaults."
    },
    {
        id: 7,
        name: "Nahargarh Fort & Sunset Point",
        category: "Panoramic Sunset & Hilltop Overlook",
        coords: [26.9378, 75.8156],
        timings: "10:00 AM - 10:00 PM (Best at 05:30 PM)",
        entryFee: { budget: 50, standard: 150, foreign: 300 },
        travelTimeFromPrev: "20 mins scenic ghat road drive (8 km)",
        transitMode: "Private Taxi / Self-drive Scooter / Cab",
        googleRating: 4.7,
        reviewsCount: "68,000+",
        proTip: "Arrive 45 minutes before sunset for the golden hour over the entire Pink City skyline from Padao rooftop cafe.",
        busAvailability: "Private shuttle cabs available from foot of hill; city bus stops at Ghat gate",
        description: "A fortress standing on the edge of the Aravalli Hills overlooking the entire city with rooftop cafes and wax museum."
    },
    {
        id: 8,
        name: "Jal Mahal (Water Palace)",
        category: "Scenic Lake Palace Viewpoint",
        coords: [26.9535, 75.8462],
        timings: "Open 24/7 (Exterior Lakefront Promenade)",
        entryFee: { budget: 0, standard: 0, foreign: 0 },
        travelTimeFromPrev: "15 mins drive downhill along Amer Road (6 km)",
        transitMode: "Bus AC-5 / Auto / Taxi",
        googleRating: 4.6,
        reviewsCount: "76,000+",
        proTip: "Enjoy camel rides, traditional street kulfi, and handicraft stalls along the lakeside paved promenade.",
        busAvailability: "Direct stop: Jal Mahal Bus Stand on AC-5 route",
        description: "A gorgeous 18th-century Rajput style palace situated in the middle of Man Sagar Lake, appearing to float on water."
    },
    {
        id: 9,
        name: "Galta Ji (Monkey Temple & Natural Springs)",
        category: "Ancient Temple Complex & Sacred Kunds",
        coords: [26.9163, 75.8596],
        timings: "05:00 AM - 09:00 PM (Daily)",
        entryFee: { budget: 0, standard: 50, foreign: 100 },
        travelTimeFromPrev: "20 mins drive (7.5 km) eastward into the Aravalli gorge",
        transitMode: "Auto Rickshaw / Taxi",
        googleRating: 4.5,
        reviewsCount: "38,000+",
        proTip: "Keep food and shiny items secured in backpacks as the resident Rhesus macaques are curious and agile.",
        busAvailability: "Buses stop at Galta Gate; 1.5 km scenic uphill walk/rickshaw to kunds",
        description: "Historic Hindu pilgrimage retreat set within a mountain pass, featuring 7 natural freshwater spring pools (kunds) and carved pavilions."
    },
    {
        id: 10,
        name: "Birla Mandir (Laxmi Narayan Temple)",
        category: "Modern White Marble Architecture",
        coords: [26.8925, 75.8155],
        timings: "06:00 AM - 12:00 PM & 03:00 PM - 09:00 PM",
        entryFee: { budget: 0, standard: 0, foreign: 0 },
        travelTimeFromPrev: "15 mins drive (5.5 km) via JLN Marg",
        transitMode: "Bus Route 2 / Auto (₹60)",
        googleRating: 4.7,
        reviewsCount: "54,000+",
        proTip: "Visit around 7:00 PM during evening aarti when the white marble temple shines under glowing floodlights below Moti Dungri fort.",
        busAvailability: "Direct stop at Birla Mandir on JLN Marg",
        description: "Pure white Makrana marble temple with intricate mythological carvings, stained glass panels, and manicured green gardens."
    },
    {
        id: 11,
        name: "Patrika Gate & Jawahar Circle",
        category: "Artistic Architecture & Musical Fountain",
        coords: [26.8172, 75.8037],
        timings: "Open 24/7 (Musical Fountain: 07:00 PM daily)",
        entryFee: { budget: 0, standard: 0, foreign: 0 },
        travelTimeFromPrev: "18 mins south on JLN Marg (8 km)",
        transitMode: "Low-Floor Bus AC-1 / Metro to Durgapura",
        googleRating: 4.8,
        reviewsCount: "71,000+",
        proTip: "Walk through each vibrant pastel archway inside the gate to photograph hand-painted Rajasthani art murals.",
        busAvailability: "Direct bus connectivity from airport and city center on JLN Marg",
        description: "Ultra-photogenic monument serving as entrance to Jawahar Circle, featuring 9 grand painted arches depicting Rajasthan history."
    },
    {
        id: 12,
        name: "Bapu Bazaar & Johari Bazaar",
        category: "Traditional Heritage Shopping & Street Food",
        coords: [26.9197, 75.8258],
        timings: "11:00 AM - 10:00 PM (Daily)",
        entryFee: { budget: 0, standard: 0, foreign: 0 },
        travelTimeFromPrev: "20 mins return drive to Walled Pink City core",
        transitMode: "E-Rickshaw / Walking / Bus 9A",
        googleRating: 4.6,
        reviewsCount: "89,000+",
        proTip: "Try signature pyaaz kachori at Rawat Mishtan Bhandar and bargain for Jaipuri quilts (razai) and camel-leather juttis.",
        busAvailability: "Badi Chaupar and Sanganeri Gate bus terminals",
        description: "Vibrant pink-walled market streets famous for authentic Mojari leather footwear, Bandhani textiles, gemstones, and block-print handicrafts."
    },
    {
        id: 13,
        name: "Sisodia Rani Ka Bagh & Palace",
        category: "Royal Terraced Garden & Water Fountains",
        coords: [26.8931, 75.8690],
        timings: "08:00 AM - 06:00 PM (Daily)",
        entryFee: { budget: 50, standard: 100, foreign: 200 },
        travelTimeFromPrev: "15 mins drive (6 km) on Jaipur-Agra Highway",
        transitMode: "Auto Rickshaw / Taxi / Bus",
        googleRating: 4.5,
        reviewsCount: "22,000+",
        proTip: "A serene getaway with minimal crowds compared to Amer; perfect for relaxing amidst painted wall frescoes.",
        busAvailability: "Agra Road buses stop right outside garden gates",
        description: "Multi-tiered landscaped royal garden built in 1728 for the Sisodia Queen, adorned with water channels, fountains, and Radha-Krishna murals."
    },
    {
        id: 14,
        name: "Panna Meena Ka Kund (Stepwell)",
        category: "Historic 16th-Century Stepwell",
        coords: [26.9912, 75.8576],
        timings: "07:00 AM - 06:00 PM (Daily)",
        entryFee: { budget: 0, standard: 0, foreign: 0 },
        travelTimeFromPrev: "5 mins drive from Amer Fort base (1.5 km)",
        transitMode: "Walking / Auto Rickshaw",
        googleRating: 4.6,
        reviewsCount: "18,500+",
        proTip: "Photograph the hypnotic symmetrical criss-cross staircases in the morning light when shadows create dramatic geometric patterns.",
        busAvailability: "Amer Fort bus drop point + 10 min walk",
        description: "Striking 16th-century square stepwell with interlocking zigzag steps, historic community gathering alcoves, and ancient water engineering."
    },
    {
        id: 15,
        name: "Chokhi Dhani Ethnic Village Resort",
        category: "Rajasthani Cultural Village & Royal Thali Feast",
        coords: [26.7663, 75.8362],
        timings: "05:00 PM - 11:00 PM (Evening Experience)",
        entryFee: { budget: 900, standard: 1200, foreign: 1500 },
        travelTimeFromPrev: "35 mins drive (18 km) south on Tonk Road",
        transitMode: "Pre-booked Cab / Uber / Shuttle",
        googleRating: 4.6,
        reviewsCount: "65,000+",
        proTip: "Arrive by 6:00 PM to enjoy camel rides, puppet shows, fire acrobatics, and Ghoomar dances before the grand traditional dining.",
        busAvailability: "Tonk Road express buses run to Vatika Mod",
        description: "Immersive 5-star ethnic cultural village celebrating Rajasthan's folk dances, magic shows, pottery making, and authentic royal dining."
    }
];

console.log("Jaipur milestones count:", jaipurMilestones.length);
